package com.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import greenden.Father;
import greenden.Son;

import com.dao.FatherDao;
import com.dao.SonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fatherDaoConfig;
    private final DaoConfig sonDaoConfig;

    private final FatherDao fatherDao;
    private final SonDao sonDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fatherDaoConfig = daoConfigMap.get(FatherDao.class).clone();
        fatherDaoConfig.initIdentityScope(type);

        sonDaoConfig = daoConfigMap.get(SonDao.class).clone();
        sonDaoConfig.initIdentityScope(type);

        fatherDao = new FatherDao(fatherDaoConfig, this);
        sonDao = new SonDao(sonDaoConfig, this);

        registerDao(Father.class, fatherDao);
        registerDao(Son.class, sonDao);
    }
    
    public void clear() {
        fatherDaoConfig.clearIdentityScope();
        sonDaoConfig.clearIdentityScope();
    }

    public FatherDao getFatherDao() {
        return fatherDao;
    }

    public SonDao getSonDao() {
        return sonDao;
    }

}
